### ISSUE TITLE
Azure devops organization

### ISSUE THREAD

**Issue by kjetilkjeka** [UAVCAN/vscode-dsdl#1]
@aasmune reports that the extension is more or less ready to being published. I've tested it, and it worked great!

The Uavcan organization [needs](https://code.visualstudio.com/docs/extensions/publish-extension) an azure dev-ops organization before its possible to publish the vscode dsdl extension. 

I only know of our Github and Gitlab organizations and don't think we have any Azure devops organization at this point. If I get the go from you, @pavel-kirienko, I will create the organization and add @aasmune with the neccesary right for him to publish this extension. If you have an account there, send me the name and I will add your used account as well.

**Comment by pavel-kirienko** [comment]
Thanks! Please go ahead. I do not have an account there.

**Comment by kjetilkjeka** [comment]
We do now have an Azure devops organization and is registered as a publisher. If you're an uavcan dev and need access, mail me with azure devops registered mail.

 @aasmune published and announced the extension on the [forum](https://forum.uavcan.org/t/dsdl-extension-for-vscode-with-syntax-highlighting/221/3)
